language: cpp
compiler: gcc
dist: trusty

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo add-apt-repository -y ppa:jonathonf/gcc
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 binutils libboost-all-dev gcc-arm-embedded
  - export CC=gcc-7
  - export CXX=g++-7
  - export AR=gcc-ar-7
  - export NM=gcc-nm-7
  - export RANLIB=gcc-ranlib-7
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - sudo sh cmake-3.9.1-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

script:
  - mkdir Firmware/build && cd Firmware/build
  - cmake .. -DTARGET_PLATFORM:STRING=x86 -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - ./build/x86/bin/unit_tests
  - cd .. && rm -rf build && mkdir build && cd build
  - cmake .. -DTARGET_PLATFORM:STRING=arm -DCMAKE_BUILD_TYPE=Release
  - make -j2

